from .backend import VcsBackend as VcsBackend
from .detect import clear_extra_detectors as clear_extra_detectors
from .detect import detect_vcs as detect_vcs
from .detect import register_detector as register_detector
from .git_backend import GitBackend as GitBackend
from .tools import VCS_TOOLS as VCS_TOOLS
from .tools import vcs_branch as vcs_branch
from .tools import vcs_diff as vcs_diff
from .tools import vcs_kind as vcs_kind
from .tools import vcs_log as vcs_log
from .tools import vcs_status as vcs_status
