from msgspec import Struct, field


class ModelConfig(Struct, omit_defaults=True):
    """Capability flags for a model within a provider."""

    text: bool = True
    image_in: bool = False
    image_out: bool = False
    audio_in: bool = False
    audio_out: bool = False
    video_in: bool = False
    video_out: bool = False
    cost_factor: float = 1.0


class ProviderConfig(Struct, tag_field="preset", omit_defaults=True):
    """Base config for all LLM providers.

    The ``preset`` tag field acts as the tagged-union discriminator
    and is auto-generated by msgspec — do not re-declare it in subclasses.
    """

    access_key_or_token: str
    url: str = ""
    models: dict[str, ModelConfig] = field(default_factory=dict)


class OpenAIProvider(ProviderConfig, tag="openai"):
    """OpenAI API provider."""


class OpenAICompatibleProvider(ProviderConfig, tag="openai-compatible"):
    """Generic OpenAI-compatible provider (e.g. vLLM, LiteLLM)."""


class AnthropicProvider(ProviderConfig, tag="anthropic"):
    """Anthropic API provider."""


class DeepseekProvider(ProviderConfig, tag="deepseek"):
    """Deepseek API provider with optional extras (e.g. convention)."""

    extras: dict[str, str] = field(default_factory=dict)


type Provider = OpenAIProvider | OpenAICompatibleProvider | AnthropicProvider | DeepseekProvider
