from typing import Any

from msgspec import Struct, field


class DatabaseConfig(Struct, omit_defaults=True):
    """Database connection configuration.

    ``url`` is ``None`` when unset. The CLI fills a durable user-data
    ``chat.db`` only for unset/empty url. Explicit ``":memory:"`` is a true
    in-memory SQLite (no rewrite).
    """

    implementation: str = "sqlite"
    url: str | None = None
    username: str | None = None
    password: str | None = None


class AgentConfig(Struct, omit_defaults=True):
    """Single-user agent profile defaults."""

    system_prompt: str = ""
    max_tool_result_chars: int = 32_000
    parallel_tools: bool = True
    confirm_destructive: bool = True
    path_denylist: list[str] = field(default_factory=list)
    max_context_tokens: int = 200_000

    # How to inject todo stack nags into model context (see agent/todo_nag.py).
    # developer | user | synthetic_tool | none  (legacy "system" → developer)
    todo_nag_strategy: str = "developer"

    # Compact / summarisation prompts (empty = use built-in defaults).
    compact_system_prompt: str = ""
    compact_user_prefix: str = ""
    compact_seed_text: str = ""


class ModelConfig(Struct, omit_defaults=True):
    """Capability flags for a model within a provider."""

    text: bool = True
    image_in: bool = False
    image_out: bool = False
    audio_in: bool = False
    audio_out: bool = False
    video_in: bool = False
    video_out: bool = False
    cost_factor: float = 1.0


class ProviderConfig(Struct, tag_field="preset", omit_defaults=True):
    """Base config for all LLM providers.

    The ``preset`` tag field acts as the tagged-union discriminator
    and is auto-generated by msgspec — do not re-declare it in subclasses.
    """

    access_key_or_token: str
    url: str = ""
    models: dict[str, ModelConfig] = field(default_factory=dict)


def _default_openai_models() -> dict[str, ModelConfig]:
    """Current OpenAI text catalog when TOML omits ``models``."""
    return {
        "gpt-5.4": ModelConfig(text=True),
        "gpt-5.4-mini": ModelConfig(text=True),
        "gpt-5.4-nano": ModelConfig(text=True),
    }


def _default_openai_provider_tools() -> list[dict[str, Any]]:
    """Hosted tools when TOML omits ``provider_tools``."""
    return [{"type": "web_search"}]


class OpenAIProvider(ProviderConfig, tag="openai"):
    """OpenAI platform provider (agent uses Responses API).

    ``provider_tools`` are hosted/provider-side tools (e.g. web_search) passed
    through to ``POST /responses`` as opaque dicts. They are **not** local
    ``ToolRegistry`` handlers and are ignored by non-OpenAI clients.

    When ``models`` is omitted in TOML, seeds a small default catalog (same idea
    as DeepSeek). Explicit ``models = {}`` stays empty (recoverable / free-form).
    When ``provider_tools`` is omitted, defaults to web_search; use
    ``provider_tools = []`` to disable hosted tools.
    """

    models: dict[str, ModelConfig] = field(default_factory=_default_openai_models)
    provider_tools: list[dict[str, Any]] = field(default_factory=_default_openai_provider_tools)


class OpenAICompatibleProvider(ProviderConfig, tag="openai-compatible"):
    """Generic OpenAI-compatible provider (e.g. vLLM, LiteLLM)."""


class AnthropicProvider(ProviderConfig, tag="anthropic"):
    """Anthropic API provider."""


def _default_deepseek_models() -> dict[str, ModelConfig]:
    """Current DeepSeek text catalog when TOML omits ``models``."""
    return {
        "deepseek-v4-flash": ModelConfig(text=True),
        "deepseek-v4-pro": ModelConfig(text=True),
    }


class DeepseekProvider(ProviderConfig, tag="deepseek"):
    """Deepseek API provider with optional extras (e.g. convention)."""

    models: dict[str, ModelConfig] = field(default_factory=_default_deepseek_models)
    extras: dict[str, str] = field(default_factory=dict)


type Provider = OpenAIProvider | OpenAICompatibleProvider | AnthropicProvider | DeepseekProvider
