from typing import Any

from msgspec import Struct, field

# Built-in agent system prompt when ``[agent].system_prompt`` is omitted.
# Set ``system_prompt = ""`` in TOML to disable. Override with a multi-line
# TOML literal (prefer '''...''' so nested " quotes are fine).
DEFAULT_SYSTEM_PROMPT = """\
You are a professional coding agent in a workspace-bound tool environment.

### Workspace
- Explore with `tree`/`listdir`/`glob_paths`/`grep_files`/`read_file` when unsure.
- Stay under the workspace (or a path from `new_temporary_workspace`). Respect path denylists.

### Files
- Prefer file tools over shell. `edit_replace` fails usually means a bad match — \
fix `old_string` or `max_replaces`; shell workarounds rarely help.
- `edit_replace` defaults to the first match; if remaining matches are reported, \
raise `max_replaces` or narrow `old_string`.
- Before `edit_lineno`, `read_file` with `with_lineno=true`.

### Commands
- Prefer `run_command` / `run_command_batch` (argv, no shell) over `bash -c` or similar.
- Several `run_command` calls in one step may run in parallel; use `run_command_batch` \
for ordered pipelines (`pipe_out` / `mix_stderr` as needed).
- Prefer `vcs_*` for status/diff/log/branch when enough.

### Humans & safety
- Prefer `ask_user_line` / `ask_user_choice` / `ask_user_form` over waiting for the next free-form turn.
- Overwrites, deletes, shells, and risky ops may require human confirm; hard denylists are not skipped by YOLO.
- Temporary scratch: `new_temporary_workspace`.

### PTY
- Use PTY for interactive/TUI, sudo, ssh, or live servers.
- Passwords and other secret input: only `ask_into_pty` (never echo secrets into `write_pty`).
- Control keys: `write_pty_keys`, not literal `write_pty` data.

### Todos
- Use the todo stack for multi-step work (LIFO groups: push related items, finish/update, \
pop the group). Open items mean unfinished work.
"""


class DatabaseConfig(Struct, omit_defaults=True):
    """Database connection configuration.

    ``url`` is ``None`` when unset. The CLI fills a durable user-data
    ``chat.db`` only for unset/empty url. Explicit ``":memory:"`` is a true
    in-memory SQLite (no rewrite).
    """

    implementation: str = "sqlite"
    url: str | None = None
    username: str | None = None
    password: str | None = None


class AgentConfig(Struct, omit_defaults=True):
    """Single-user agent profile defaults."""

    system_prompt: str = DEFAULT_SYSTEM_PROMPT
    max_tool_result_chars: int = 32_000
    parallel_tools: bool = True
    confirm_destructive: bool = True
    path_denylist: list[str] = field(default_factory=list)
    max_context_tokens: int = 200_000

    # How to inject todo stack nags into model context (see agent/todo_nag.py).
    # developer | user | synthetic_tool | none  (legacy "system" → developer)
    todo_nag_strategy: str = "developer"

    # Compact / summarisation prompts (empty = use built-in defaults).
    compact_system_prompt: str = ""
    compact_user_prefix: str = ""
    compact_seed_text: str = ""


class ModelConfig(Struct, omit_defaults=True):
    """Capability flags for a model within a provider."""

    text: bool = True
    image_in: bool = False
    image_out: bool = False
    audio_in: bool = False
    audio_out: bool = False
    video_in: bool = False
    video_out: bool = False
    cost_factor: float = 1.0


class HttpTimeoutConfig(Struct, omit_defaults=True):
    """Per-provider HTTP timeouts (seconds) for the LLM API client.

    TOML examples::

        timeout = 120
        timeout = { connect = 10, read = 600 }

    ``connect`` bounds TCP/TLS setup; ``read`` bounds idle wait between response
    bytes (SSE streams can run longer than *read* as long as chunks keep arriving).
    Omitted fields use product defaults (10s connect / 600s read).
    """

    connect: float | None = None
    read: float | None = None


class ProviderConfig(Struct, tag_field="preset", omit_defaults=True):
    """Base config for all LLM providers.

    The ``preset`` tag field acts as the tagged-union discriminator
    and is auto-generated by msgspec — do not re-declare it in subclasses.
    """

    access_key_or_token: str
    url: str = ""
    models: dict[str, ModelConfig] = field(default_factory=dict)
    # float = single timeout for the session; table = connect/read split; omit = defaults.
    timeout: float | HttpTimeoutConfig | None = None


def _default_openai_models() -> dict[str, ModelConfig]:
    """Current OpenAI text catalog when TOML omits ``models``."""
    return {
        "gpt-5.4": ModelConfig(text=True),
        "gpt-5.4-mini": ModelConfig(text=True),
        "gpt-5.4-nano": ModelConfig(text=True),
    }


def _default_openai_provider_tools() -> list[dict[str, Any]]:
    """Hosted tools when TOML omits ``provider_tools``."""
    return [{"type": "web_search"}]


class OpenAIProvider(ProviderConfig, tag="openai"):
    """OpenAI platform provider (agent uses Responses API).

    ``provider_tools`` are hosted/provider-side tools (e.g. web_search) passed
    through to ``POST /responses`` as opaque dicts. They are **not** local
    ``ToolRegistry`` handlers and are ignored by non-OpenAI clients.

    When ``models`` is omitted in TOML, seeds a small default catalog (same idea
    as DeepSeek). Explicit ``models = {}`` stays empty (recoverable / free-form).
    When ``provider_tools`` is omitted, defaults to web_search; use
    ``provider_tools = []`` to disable hosted tools.
    """

    models: dict[str, ModelConfig] = field(default_factory=_default_openai_models)
    provider_tools: list[dict[str, Any]] = field(default_factory=_default_openai_provider_tools)


class OpenAICompatibleProvider(ProviderConfig, tag="openai-compatible"):
    """Generic OpenAI-compatible provider (e.g. vLLM, LiteLLM)."""


class AnthropicProvider(ProviderConfig, tag="anthropic"):
    """Anthropic API provider."""


def _default_deepseek_models() -> dict[str, ModelConfig]:
    """Current DeepSeek text catalog when TOML omits ``models``."""
    return {
        "deepseek-v4-flash": ModelConfig(text=True),
        "deepseek-v4-pro": ModelConfig(text=True),
    }


class DeepseekProvider(ProviderConfig, tag="deepseek"):
    """Deepseek API provider with optional extras (e.g. convention)."""

    models: dict[str, ModelConfig] = field(default_factory=_default_deepseek_models)
    extras: dict[str, str] = field(default_factory=dict)


type Provider = OpenAIProvider | OpenAICompatibleProvider | AnthropicProvider | DeepseekProvider
